name: Publish

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release-nifs:
    uses: leandrocp/github-actions/.github/workflows/nif-release.yml@main
    with:
      project-name: mdex_native_nif
      project-dir: native/mdex_native_nif
      feature-variants: '[{"features":"lumis","variant":"lumis"},{"features":"syntect","variant":"syntect"},{"features":"","variant":""}]'

  hex-publish:
    needs: release-nifs
    if: startsWith(github.ref, 'refs/tags/v')
    uses: leandrocp/github-actions/.github/workflows/hex-publish.yml@main
    with:
      install-rust: true
      pre-publish-command: MDEX_NATIVE_BUILD=1 mix rustler_precompiled.download MDExNative.Native --all --print && mix escript.install hex ex_doc --force
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
